#!/usr/bin/env sh

set -e

cd /var/www/html

if [ -x ./vendor/bin/shopwell-deployment-helper ]; then
    exec ./vendor/bin/shopwell-deployment-helper run
fi

echo "### ERROR ###"
echo ""
echo "### The setup scripts are removed ###"
echo "### Please install the Shopwell Deployment Helper using composer require shopwell/deployment-helper to continue ###"
echo "### For more information see https://developer.shopwell.cn/docs/guides/hosting/installation-updates/deployments/deployment-helper.html ###"
echo ""
echo "### ERROR ###"
echo ""

exit 1
